### ISSUE TITLE
Collapse control stops responding when toggled and not visible

### ISSUE THREAD

**Issue by azreal1983** [Fabi0San/DuCalibrator#10]
![Screenshot 2020-06-26 at 19 35 39](https://user-images.githubusercontent.com/63295663/85889982-67caec80-b7e4-11ea-84cf-612daec1dce8.png)
Calibration RMS: 0.080 Min: -0.276 Max: 0.240
but cannot see what is changing.

**Comment by Fabi0San** [comment]
I've seen this happen when the probing finishes and the tab is not active.
I blame the javascript collapse control I used.
We could look into using a different solution more friendly to KO bindings.
